### ISSUE TITLE
ZookeeperHealthConfig @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)？

### ISSUE THREAD

**Issue by zhaiyuyong** [spring-cloud/spring-cloud-zookeeper#81] opened 2016-05-18 01:57 UTC
```
       2016-05-18 09:54:04 [ERROR][main]:org.springframework.boot.SpringApplication [run:338] Application startup failed
java.lang.IllegalStateException: Error processing condition on org.springframework.cloud.zookeeper.ZookeeperAutoConfiguration$ZookeeperHealthConfig.zookeeperHealthIndicator
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:58) ~[spring-boot-autoconfigure-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:190) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:318) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at com.geping.gateway.GateWayApplication.main(GateWayApplication.java:84) [bin/:na]
Caused by: java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)
	at org.springframework.util.Assert.isTrue(Assert.java:65) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:232) ~[spring-boot-autoconfigure-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:93) ~[spring-boot-autoconfigure-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45) ~[spring-boot-autoconfigure-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	... 16 common frames omitted
2016-05-18 09:54:04 [INFO][main]:o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext [doClose:862] Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d373bcf: startup date [Wed May 18 09:42:34 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@57a3e26a
2016-05-18 09:54:04 [WARN][main]:o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext [doClose:872] Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d373bcf: startup date [Wed May 18 09:42:34 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@57a3e26a
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at com.geping.gateway.GateWayApplication.main(GateWayApplication.java:84) [bin/:na]
2016-05-18 09:54:04 [WARN][main]:o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext [doClose:880] Exception thrown from LifecycleProcessor on context close
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d373bcf: startup date [Wed May 18 09:42:34 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@57a3e26a
	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:357) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:150) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:836) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at com.geping.gateway.GateWayApplication.main(GateWayApplication.java:84) [bin/:na]
```

        @Configuration
	@ConditionalOnClass(Endpoint.class)
	protected static class ZookeeperHealthConfig {
		@Bean
		@ConditionalOnMissingBean
		@ConditionalOnEnabledHealthIndicator("zookeeper")
		public ZookeeperHealthIndicator zookeeperHealthIndicator(CuratorFramework curator) {
			return new ZookeeperHealthIndicator(curator);
		}
	}

**Comment by jfwork** [comment] 2016-05-20 11:07
Having the same issue with spring-boot:1.3.2.RELEASE

**Comment by spencergibb** [comment] 2016-05-20 18:57
Without your maven or gradle config or a project that reproduces the problem, we'll be unable to help.

**Comment by zhaiyuyong** [comment] 2016-05-23 10:18
compile ('org.springframework.boot:spring-boot-starter-web:' + 1.2.5.RELEASE)
compile 'org.springframework.boot:spring-boot-starter-actuator:' + 1.2.5.RELEASE
compile 'org.springframework.cloud:spring-cloud-starter-zuul:1.1.0.RELEASE'
compile ('org.springframework.cloud:spring-cloud-starter-zookeeper-discovery:1.0.0.RELEASE'){
			exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'}

i am sorry，i can not reproduce

**Comment by zhaiyuyong** [comment] 2016-05-23 10:30
spring-cloud-netflix-core version 1.1.0.RELEASE has org.springframework.cloud.netflix.eureka package

**Comment by marcingrzejszczak** [comment] 2016-05-23 10:31
The code that you've provided obviously doesn't compile so it's difficult to guess what you've been doing. Also you're manually setting versions and haven't provided the full build configuration so we don't know what is in which version. 

Everything seems to prove that you have a boot version mismatch. Without your sample project it's close to impossible to help you.

**Comment by ktong** [comment] 2016-06-06 18:39
Met this issue to. It probably causes line 55 in @ConditionalOnMissingBean without any parameters https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/ZookeeperDiscoveryClientConfiguration.java

**Comment by spencergibb** [comment] 2016-06-06 18:50
@ktong no, `@ConditionalOnMissingBean public ZookeeperServiceDiscovery ...` means conditional on missing bean of type `ZookeeperServiceDiscovery`.

@ktong as we've mentioned before, without a sample project that reproduces the problem, there's not much we can do to help.

**Comment by ktong** [comment] 2016-06-06 19:22
To create BeanSearchSpec  at line 111 in https://github.com/spring-projects/spring-boot/blob/v1.3.5.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnBeanCondition.java,  @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation). But there is nothing at line 55 in https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/ZookeeperDiscoveryClientConfiguration.java

**Comment by spencergibb** [comment] 2016-06-06 19:23
> @ktong as we've mentioned before, without a sample project that reproduces the problem, there's not much we can do to help.

**Comment by marcingrzejszczak** [comment] 2016-07-19 19:35
ping?

**Comment by ktong** [comment] 2016-07-19 20:11
Found the reason and fixed it. You may close this issue.

**Comment by marcingrzejszczak** [comment] 2016-07-19 21:03
Ok!

**Closed by marcingrzejszczak** 2016-07-19 21:03 UTC
Labels: waiting for feedback
