### ISSUE TITLE
Possible to Update Curator? Old Guava Dependancies

### ISSUE THREAD

**Issue by thartybsb** [spring-cloud/spring-cloud-zookeeper#157] opened 2018-01-15 15:12 UTC
Question:
 
Would it be possible to get an updated version of Curator? Version 2.11.1 uses a somewhat old Guava (circa 2014). There are method signature updates in later versions of Guava. When the newer version of Guava is on the class path you'll get java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.  

+--- org.springframework.cloud:spring-cloud-starter-zookeeper-config:1.1.3.RELEASE
|    \--- org.apache.curator:curator-recipes:2.11.1
|         \--- org.apache.curator:curator-framework:2.11.1
|              \--- org.apache.curator:curator-client:2.11.1
|                   +--- org.apache.zookeeper:zookeeper:3.4.8
|                   |    +--- org.slf4j:slf4j-api:1.6.1 -> 1.7.25
|                   |    \--- jline:jline:0.9.94
|                   +--- com.google.guava:guava:16.0.1  :(
 
Current Workaround: Add a dependency for org.apache.curator:curator-recipes:3.3.0

**Comment by spencergibb** [comment] 2018-01-15 15:29
Duplicate of #109

**Closed by spencergibb** 2018-01-15 15:29 UTC
